### ISSUE TITLE
Can this component play audio streams?

### ISSUE THREAD

**Issue by homejun** [JanAukToy/JAudioLib#7]
Can this component play audio streams?

**Comment by JanAukToy** [comment]
This does not support audio streaming playback.

If PCM data is sent over TCP/UDP, implementing a server-side component would make it possible. However, audio streams are typically encoded and further wrapped in a protocol.

Therefore, to receive and play audio with this library, you would need to parse the protocol, decode the audio codec or format, convert it to PCM data, and pass it on as renderable data. For this, tools like [FFmpeg](https://www.ffmpeg.org/) would be necessary.

For something that can parse the protocol, decode, and handle playback, Delphi libraries like [BASS](https://www.un4seen.com/) or free software such as [VLC Player](https://www.videolan.org/vlc/index.ja.html).

**Comment by JanAukToy** [comment]
I have created an audio streaming client using FFmpeg. Please check the [feature/audiostreaming](https://github.com/JanAukToy/JAudioLib/tree/feature/audiostreaming) branch (the sample is located in [JAudioLib\Demo\AudioStreaming\Client\AudioStreamingClientWithFFmpeg](https://github.com/JanAukToy/JAudioLib/tree/feature/audiostreaming/Demo/AudioStreaming/Client/AudioStreamingClientWithFFmpeg)).

You can play the stream by passing the generated SDP file to VLC Player. The client supports the free Opus codec.

Server implementation for decoding with FFmpeg and rendering audio with WASAPI will be added later.

**Comment by JanAukToy** [comment]
An example of a server implementation using VLC Player has been added and merged into the main repository.
